- platform: smartir
  name: Masterbed AC
  unique_id: masterbed_ac
  device_code: 1003
  delay: 0.5
  controller_data: remote.ir_blaster_master_bedroom_remote
  temperature_sensor: sensor.masterbedroom_masterbed_temperature
  humidity_sensor: sensor.masterbedroom_masterbed_humidity

- platform: smartir
  name: Kid's AC
  unique_id: kids_ac
  device_code: 1003
  delay: 0.5
  controller_data: remote.otto_s_room_remote_control_remote
  temperature_sensor: sensor.study_kidsroom_temperature
  humidity_sensor: sensor.study_kidsroom_humidity

- platform: smartir
  name: Study AC
  unique_id: study_ac
  device_code: 1003
  delay: 0.5
  controller_data: remote.henrys_room_ir_blaster_remote
  temperature_sensor: sensor.study_study_temperature
  humidity_sensor: sensor.study_study_humidity

- platform: smartir
  name: Living Room AC
  unique_id: living_room_ac
  device_code: 1002
  delay: 0.5
  controller_data: remote.livingroom_irblaster_remote
  temperature_sensor: sensor.living_room_temperature_offset #sensor.ble_temperature_kitchen_temp_humidity_sensor
  humidity_sensor: sensor.livingroom_irblaster_humidity
